# docker-compose.yml

services:
  clever-lama:
    build: .
    container_name: clever-lama
    ports:
      - "11434:11434"
    environment:
      - API_BASE_URL=${API_BASE_URL:-https://api.aitunnel.ru/v1}
      - API_KEY=${API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CACHE_DURATION_MINUTES=${CACHE_DURATION_MINUTES:-10}
      - HOST=0.0.0.0
      - PORT=11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
